### ISSUE TITLE
Implement Cross Site Scripting (XSS) Security to the Server App 

### ISSUE THREAD

**Issue by hyperloo** [hyperloo/UrlCompressor-Server#1]
**How is the feature you adding to the App is related to the issue? Please describe.**
This Security will make the Server secure from the Javascript Injection to the server as well as DB.

**Describe the method/ package through which you have implemented the solution.**
Mention the details about the Package or the method you have used to overcome the issue.

And don't forget to ⭐ the repo!😁

**Comment by je-poy** [comment]
Hi @HyperLoo , i have a pull request with regards to this. You may check it here. Hope it helps [https://github.com/HyperLoo/UrlCompressor-Server/pull/5](https://github.com/HyperLoo/UrlCompressor-Server/pull/5)

**Comment by hyperloo** [comment]
Hey @je-poy,
What kind of response does it give to any XSS attack?

**Comment by je-poy** [comment]
If there is a XSS attack, it still gives the normal response, tho helmet package will sanitize the request data and will send proper response headers to the client's browser telling not to execute the injected script.

as for my checking, use the older version of Helmet Package, probably lower than version 4. since it turns of the xssFiltering header
